### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by pennywisdom65** [MokkaSchnalle/macOS-Dell-5411-5511#1]
Hi there,

I used your config and files on my 5411 but ended up having several issues I have been able to resolve with different ACPI files and disabling the dedicated GPU. Thank you for this! 

One thing I cannot resolve is the trackpad being extremely jumpy and very slow boot times (3-5 min with an nvme). Was curious if you had made any progress on your "to-do" list you would be willing to share? Thanks!

**Comment by MokkaSchnalle** [comment]
Hi,

thanks for using my config 😊
you have a dedicated GPU in there? Interesting. Whatevergreen „disable-external-gpu“ and agdpmod=vit9696 should be fine.

The trackpad is really buggy, I know. The problem is that this Machine has a buggy GPIO implementation.
I was only successful with polling mode. But the right Click isn’t working. Left click only when touching the pad simultaneously and can’t do drag and drop with releasing your fingers.

I will push an update with latest Opencore and Kexts this Evening.

3-5 minutes is really slow. Not normal. Please use DebugEnhancer and -v to check for blockers while booting.
My computer is up after 40 secs without FileVault and about 1min with FileVault. FileVault is also buggy on this machine. I don’t know why. It takes 10-40 secs to show the password screen.

**Comment by MokkaSchnalle** [comment]
And may you check if you can change UEFI variables via ru.efi or setup_var? That would be really interesting.

It is not working for me. But I think due to a bios password lock. This is my office computer.

**Comment by pennywisdom65** [comment]
That’s great thanks! If updated kexts and opencore are the only changes, please don’t worry as I have already done so. Just wasn’t sure about the trackpad mostly. I was going to take some time and try to play with the GPIO pinning when I have a chance.

I was able to disable the GPU by using -wegnoegpu (or something to that effect). I didn’t even realized it had one until my work ordered it.

Will definitely be digging into the slow boot. I’ve left the debugenhancer kext and also overwrote opencore with the debug version to hopefuly parse through the logs at some point.

Sure, I’ll give the UEFI variables a shot too. This is also my work computer but absolutely nothing is locked out fortunately.

**Comment by pennywisdom65** [comment]
I did try the tool and unfortunately it said it has a locked register.

**Comment by MokkaSchnalle** [comment]
So you have used setup_var, setup_var2 setup_var3 and ru.efi?
Interesting. Then it is not related to my UEFI password.

**Comment by MokkaSchnalle** [comment]
I have found the issue.
The DVMT value is inside the "SaSetup" UEFI variable. Changing with ru.efi worked perfectly. I will provide an update to my repo this week :)

**Comment by pennywisdom65** [comment]
> I have found the issue.
> The DVMT value is inside the "SaSetup" UEFI variable. Changing with ru.efi worked perfectly. I will provide an update to my repo this week :)

Sorry I wasn’t able to get that going, nice find though! What does that allow you to do now that you couldn’t before?

**Comment by MokkaSchnalle** [comment]
You can set the iGPU DVMT pre-allocated to 64MB (instead of 32MB). This will enable 4K@60Hz or in my case a LG Ultra Wide display (3840x1600@85Hz).

In addition, you can disable the CFG/MSR Lock. Then macOS is able to do native Power Management without Kernel patches. One more thing on the road to vanilla 😉

**Comment by pennywisdom65** [comment]
Very nice! Congrats!

**Comment by MokkaSchnalle** [comment]
My update is online.

Still outstanding: GPIO fixes

**Comment by pennywisdom65** [comment]
Thanks for pushing the update - I tried to boot a fresh installer and get a stalled boot at varying points of the process, never actually letting me into the installer. Tried changing a few boot options, and some things I could think of but never got past the boot process.

Glad you've made progress on your machine though!

**Comment by MokkaSchnalle** [comment]
Have you changed the UEFI settings? Are you using a DW1830 or DW1560 Wireless card?
My new commit requires disabled CFG Lock and DVMT 64MB

Just boot with -v and post the screen when it is stuck.

**Comment by pennywisdom65** [comment]
![IMG-2069](https://user-images.githubusercontent.com/4468220/121252307-d5e1b580-c875-11eb-80f3-62620d4027ca.jpg)
![IMG-2070](https://user-images.githubusercontent.com/4468220/121252315-d8440f80-c875-11eb-828f-4ed30949d91e.jpg)
Here are a couple examples, it changes slightly each time. I have changed my bios and applied teh new findings to cfg lock as I have the same bios version but it will not boot. Strange since it worked ok with your previous commit.
